name: Checkov

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform_azure,terraform_ci
          framework: terraform

  trigger-jenkins:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Trigger Jenkins webhook
        run: |
          
          CRUMB=$(curl -s "http://4.193.154.62:8080/crumbIssuer/api/json" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['crumbRequestField']+':'+d['crumb'])")

          
          curl -f -X POST "${{ secrets.JENKINS_WEBHOOK_URL }}" \
            -H "$CRUMB" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            --max-time 30